[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  package = "@commandbar/netlify-plugin-commandbar"


[plugins.inputs.linkCommands]
  "Go to dashboard" = '/dashboard' // relative link
  "Go to stack overflow" = 'https://stackoverflow.com' // aboslute link